import { VideoType } from "./enums"

  export const topTwelveVideos = [
    {
      videoId: "tech-1",
      thumbnailImgUrl: "https://picsum.photos/seed/tech1/400/225",
      title: "Building a Modern React App from Scratch",
      views: "1.2M views",
      uploadedTime: "2 days ago",
      channelName: "CodeCraft Academy",
      channelImgUrl: "https://picsum.photos/seed/channel1/64/64",
      videoViews: 1200345,
      videoUrl: "https://www.youtube.com/watch?v=tech1",
      channelUrl: "https://www.youtube.com/@codecraftacademy",
      videoType: VideoType.Video,
    },
    {
      videoId: "design-1",
      thumbnailImgUrl: "https://picsum.photos/seed/design1/400/225",
      title: "10 UX Principles for Better Products",
      views: "845K views",
      uploadedTime: "1 week ago",
      channelName: "Pixel Perfect",
      channelImgUrl: "https://picsum.photos/seed/channel2/64/64",
      videoViews: 845210,
      videoUrl: "https://www.youtube.com/watch?v=design1",
      channelUrl: "https://www.youtube.com/@pixelperfect",
      videoType: VideoType.Video,
    },
    {
      videoId: "business-1",
      thumbnailImgUrl: "https://picsum.photos/seed/business1/400/225",
      title: "How to Start a SaaS in 2025",
      views: "392K views",
      uploadedTime: "3 weeks ago",
      channelName: "Startup Stories",
      channelImgUrl: "https://picsum.photos/seed/channel3/64/64",
      videoViews: 392110,
      videoUrl: "https://www.youtube.com/watch?v=business1",
      channelUrl: "https://www.youtube.com/@startupstories",
      videoType: VideoType.Video,
    },
    {
      videoId: "ent-1",
      thumbnailImgUrl: "https://picsum.photos/seed/entertainment1/400/225",
      title: "24 Hours in Tokyo: Cinematic Travel Film",
      views: "2.3M views",
      uploadedTime: "5 days ago",
      channelName: "City Lights",
      channelImgUrl: "https://picsum.photos/seed/channel4/64/64",
      videoViews: 2300456,
      videoUrl: "https://www.youtube.com/watch?v=ent1",
      channelUrl: "https://www.youtube.com/@citylights",
      videoType: VideoType.Video,
    },
    {
      videoId: "health-1",
      thumbnailImgUrl: "https://picsum.photos/seed/health1/400/225",
      title: "5 Morning Habits That Changed My Life",
      views: "678K views",
      uploadedTime: "4 days ago",
      channelName: "Mind & Motion",
      channelImgUrl: "https://picsum.photos/seed/channel5/64/64",
      videoViews: 678432,
      videoUrl: "https://www.youtube.com/watch?v=health1",
      channelUrl: "https://www.youtube.com/@mindandmotion",
      videoType: VideoType.Video,
    },
    {
      videoId: "tech-2",
      thumbnailImgUrl: "https://picsum.photos/seed/tech2/400/225",
      title: "Building a Modern React App from Scratch",
      views: "1.2M views",
      uploadedTime: "2 days ago",
      channelName: "CodeCraft Academy",
      channelImgUrl: "https://picsum.photos/seed/channel1/64/64",
      videoViews: 1200345,
      videoUrl: "https://www.youtube.com/watch?v=tech1",
      channelUrl: "https://www.youtube.com/@codecraftacademy",
      videoType: VideoType.Video,
    },
    {
      videoId: "design-2",
      thumbnailImgUrl: "https://picsum.photos/seed/design2/400/225",
      title: "10 UX Principles for Better Products",
      views: "845K views",
      uploadedTime: "1 week ago",
      channelName: "Pixel Perfect",
      channelImgUrl: "https://picsum.photos/seed/channel2/64/64",
      videoViews: 845210,
      videoUrl: "https://www.youtube.com/watch?v=design1",
      channelUrl: "https://www.youtube.com/@pixelperfect",
      videoType: VideoType.Video,
    },
    {
      videoId: "business-2",
      thumbnailImgUrl: "https://picsum.photos/seed/business2/400/225",
      title: "How to Start a SaaS in 2025",
      views: "392K views",
      uploadedTime: "3 weeks ago",
      channelName: "Startup Stories",
      channelImgUrl: "https://picsum.photos/seed/channel3/64/64",
      videoViews: 392110,
      videoUrl: "https://www.youtube.com/watch?v=business1",
      channelUrl: "https://www.youtube.com/@startupstories",
      videoType: VideoType.Video,
    },
    {
      videoId: "ent-2",
      thumbnailImgUrl: "https://picsum.photos/seed/entertainment2/400/225",
      title: "24 Hours in Tokyo: Cinematic Travel Film",
      views: "2.3M views",
      uploadedTime: "5 days ago",
      channelName: "City Lights",
      channelImgUrl: "https://picsum.photos/seed/channel4/64/64",
      videoViews: 2300456,
      videoUrl: "https://www.youtube.com/watch?v=ent1",
      channelUrl: "https://www.youtube.com/@citylights",
      videoType: VideoType.Video,
    },
    {
      videoId: "health-2",
      thumbnailImgUrl: "https://picsum.photos/seed/health2/400/225",
      title: "5 Morning Habits That Changed My Life",
      views: "678K views",
      uploadedTime: "4 days ago",
      channelName: "Mind & Motion",
      channelImgUrl: "https://picsum.photos/seed/channel5/64/64",
      videoViews: 678432,
      videoUrl: "https://www.youtube.com/watch?v=health1",
      channelUrl: "https://www.youtube.com/@mindandmotion",
      videoType: VideoType.Video,
    },
  ]

  export const topTwelveShorts = [
    {
      videoId: "short-tech-1",
      thumbnailImgUrl: "https://picsum.photos/seed/shorttech1/300/540",
      title: "VS Code Shortcuts You Need to Know",
      views: "1.9M views",
      uploadedTime: "1 day ago",
      channelName: "Dev Snacks",
      channelImgUrl: "https://picsum.photos/seed/shortchannel1/64/64",
      videoViews: 1900456,
      videoUrl: "https://www.youtube.com/shorts/shorttech1",
      channelUrl: "https://www.youtube.com/@devsnacks",
      videoType: VideoType.Short,
    },
    {
      videoId: "short-design-1",
      thumbnailImgUrl: "https://picsum.photos/seed/shortdesign1/300/540",
      title: "3 Color Palette Hacks in 30 Seconds",
      views: "521K views",
      uploadedTime: "2 days ago",
      channelName: "Design Bites",
      channelImgUrl: "https://picsum.photos/seed/shortchannel2/64/64",
      videoViews: 521340,
      videoUrl: "https://www.youtube.com/shorts/shortdesign1",
      channelUrl: "https://www.youtube.com/@designbites",
      videoType: VideoType.Short,
    },
    {
      videoId: "short-fun-1",
      thumbnailImgUrl: "https://picsum.photos/seed/shortfun1/300/540",
      title: "Desk Setup Glow Up in 20 Seconds",
      views: "812K views",
      uploadedTime: "6 hours ago",
      channelName: "Desk Dreams",
      channelImgUrl: "https://picsum.photos/seed/shortchannel3/64/64",
      videoViews: 812045,
      videoUrl: "https://www.youtube.com/shorts/shortfun1",
      channelUrl: "https://www.youtube.com/@deskdreams",
      videoType: VideoType.Short,
    },
    {
      videoId: "short-sport-1",
      thumbnailImgUrl: "https://picsum.photos/seed/shortsport1/300/540",
      title: "Insane Half-Court Buzzer Beater",
      views: "3.1M views",
      uploadedTime: "3 days ago",
      channelName: "Court Side Clips",
      channelImgUrl: "https://picsum.photos/seed/shortchannel4/64/64",
      videoViews: 3100789,
      videoUrl: "https://www.youtube.com/shorts/shortsport1",
      channelUrl: "https://www.youtube.com/@courtsideclips",
      videoType: VideoType.Short,
    },
    {
      videoId: "short-travel-1",
      thumbnailImgUrl: "https://picsum.photos/seed/shorttravel1/300/540",
      title: "Sunrise Over the Alps in 15 Seconds",
      views: "467K views",
      uploadedTime: "5 days ago",
      channelName: "Trail Tales",
      channelImgUrl: "https://picsum.photos/seed/shortchannel5/64/64",
      videoViews: 467902,
      videoUrl: "https://www.youtube.com/shorts/shorttravel1",
      channelUrl: "https://www.youtube.com/@trailtales",
      videoType: VideoType.Short,
    },
  ]
